markdown_ext: "md"
include: []
permalink: /:path/
theme: jekyll-theme-cayman
defaults:
  - scope: 
      path: ""
      type: "pages"
    values:
      layout: "default"
      title: "kunalkeshan | journal"
      description: "Sharing my learnings, document helpful guides, and keep a record of various insights I come across. This space is dedicated to my continuous learning journey and serves as a valuable resource for anyone interested in the topics I explore."
